imaqreset;

vid = videoinput('winvideo');
triggerconfig(vid,'manual');
cam.TriggerRepeat = Inf;
cam.FramesPerTrigger = 1;

hFig = figure('Toolbar','none',...
       'Menubar', 'none',...
       'NumberTitle','Off',...
       'Name','Guidance System');

uicontrol('String', 'Start Preview',...
    'Callback', 'preview(vid)',...
    'Units','normalized',...
    'Position',[0 0 0.15 .07],...
    'FontSize',10);

uicontrol('String', 'Stop Preview',...
    'Callback', 'stoppreview(vid)',...
    'Units','normalized',...
    'Position',[.17 0 .15 .07],...
    'FontSize',10);

uicontrol('String', 'Get Image',...
    'Interruptible','on',...
    'Callback', @GetImg_Fcn,...
    'Units','normalized',...
    'Position',[.34 0 .15 .07],...
    'FontSize',10);

uicontrol('String', 'Show Image',...
    'Callback', 'imshow(im)',...
    'Units','normalized',...
    'Position',[.51 0 .15 .07],...
    'FontSize',10);

uicontrol('String', 'Get PtCloud',...
    'Callback', 'stoppreview(vid)',...
    'Units','normalized',...
    'Position',[.68 0 .15 .07],...
    'FontSize',10);

uicontrol('String', 'Close',...
    'Callback', 'close(gcf)',...
    'Units','normalized',...
    'Position',[0.85 0 .15 .07],...
    'FontSize',10);

% Create the text label for the timestamp
hTextLabel = uicontrol('style','text','String','Timestamp', ...
    'Units','normalized',...
    'Position',[0.88 0.94 .13 .05]);

% Create the image object in which you want to
% display the video preview data.
vidRes = vid.VideoResolution;
imWidth = vidRes(1);
imHeight = vidRes(2);
nBands = vid.NumberOfBands;
hImage = image( zeros(imHeight, imWidth/2, nBands) );

% Specify the size of the axes that contains the image object
% so that it displays the image at the right resolution and
% centers it in the figure window.
figSize = get(hFig,'Position');
figWidth = figSize(3);
figHeight = figSize(4);
gca.unit = 'pixels';
gca.position = [ ((figWidth - imWidth)/2)... 
               ((figHeight - imHeight)/2)...
               imWidth imHeight ];

% Set up the update preview window function.
setappdata(hImage,'UpdatePreviewWindowFcn',@mypreview_fcn);

% Make handle to text label available to update function.
setappdata(hImage,'HandleToTimestampLabel',hTextLabel);

preview(vid, hImage);

function mypreview_fcn(obj,event,himage)
% Example update preview window function.

% Get timestamp for frame.
tstampstr = event.Timestamp;

% Get handle to text label uicontrol.
ht = getappdata(himage,'HandleToTimestampLabel');

% Set the value of the text label.
ht.String = tstampstr;

% Display image data.
himage.CData = event.Data;

end

function GetImg_Fcn(obj,event,himage)

trigger(obj);
im = getdata(obj);

end
